#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE[0]}")" || exit

git pull origin master;

function doIt() {
  rsync --exclude ".git/" \
    --exclude "bootstrap" \
    --exclude "README.md" \
    -avh --no-perms . ~;

  # shellcheck source=/dev/null
  source ~/.profile;
}

if [ "$1" == "--force" ] || [ "$1" == "-f" ]; then
  doIt;
else
  read -rp "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1;
  echo "";
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    doIt;
  fi;
fi;
unset doIt;
